In [ ]:
# imports
import numpy as np
import sympy as sp
from sympy.vector import CoordSys3D, cross
from scipy.integrate import quad

External Torque Analysis

In [ ]:
M = sp.symbols('M', real=True)
R = sp.symbols('R', real=True)
H = sp.symbols('H', real=True)
t = sp.symbols('t', real=True)
J = sp.Matrix([
    [.5*M*R**2, 0, 0],
    [0, (1/12)*M*(3*R**2 + H**2), 0],
    [0, 0, (1/12)*M*(3*R**2 + H**2)]
])
wb = sp.Matrix([
    [2],
    [t],
    [sp.sin(t)]
])
wb_dot = sp.Matrix([
    [0],
    [1],
    [sp.cos(t)]
])

T = J @ wb_dot + cross(wb, J @ wb) + 

Starship Heavy Example

In [5]:
theta = sp.symbols('theta', real=True)
r = sp.symbols('r', real=True)
H = sp.symbols('H', real=True)
h = sp.symbols('h', real=True)
R = sp.symbols('R', real=True)
M = sp.symbols('M', real=True)

J11_dr = sp.integrate((r*sp.sin(theta))**2 + r**2, (r, 0, R))
J11_dtheta = sp.integrate(J11_dr, (theta, 0, 2*np.pi))
J11 = sp.integrate(J11_dtheta, (h, 0, H))
print(sp.simplify(J11))

J = sp.Matrix([
    [(1/4)*M*R**2, 0, 0],
    [0, (1/4)*M*R**2+(1/3)*M*H**2, 0],
    [0, 0, (1/2)*M*R**2]
])

J_real = J.subs({
    R: 4.5,
    H: 71,
    M: 180*10**3
})
print(J_real)

3.14159265358979*H*R**3
Matrix([[911250.000000000, 0, 0], [0, 303371250.000000, 0], [0, 0, 1822500.00000000]])


In [7]:
# initial values
T0 = np.array([
    [0],
    [0],
    [490.5]
])
omega = np.array([
    [0],
    [0],
    [0.005]
])
eulerangs = np.deg2rad(np.array([
    [0],
    [0],
    [45]
]))
h = 71
r = 4.5
thrust = 9.81 * 10**3
dmass = 160e3
fmass = 20e3
mtot = dmass + fmass



In [14]:
from scipy.integrate import solve_ivp
import numpy as np

import src.AERO.AERO320.DynCon_Functions as df


def body_rates_to_quat_dot(q, omega):
    """
    Compute quaternion derivative from body angular rates.

    Parameters
    ----------
    q : array-like, shape (4,)
        Quaternion [q0, q1, q2, q3] (scalar-first convention).
    omega : array-like, shape (3,)
        Body rates [p, q, r] in radians per second.

    Returns
    -------
    q_dot : ndarray, shape (4,)
        Time derivative of the quaternion.
    """
    q0, q1, q2, q3 = q
    p, q_, r = omega

    # Quaternion rate matrix
    Omega = np.array([
        [0,   -p,  -q_,  -r],
        [p,    0,   r,  -q_],
        [q_,  -r,   0,   p],
        [r,    q_, -p,   0]
    ])

    q_dot = 0.5 * Omega @ np.array([q0, q1, q2, q3])
    return q_dot

q0 = df.euler321_to_quat(eulerangs[0], eulerangs[1], eulerangs[2]).T
print(q0)
t0, tf = 0.0, 45.0
t_eval = np.linspace(t0, tf, 1001)

[t, x] = solve_ivp(fun=lambda t, x: body_rates_to_quat_dot(q, omega),
                   t_span=(t0, tf), y0=q0, t_eval=t_eval,
                   rtol=1e-9, atol=1e-12, method='RK45')

[[0.92387953 0.         0.         0.38268343]]


ValueError: `y0` must be 1-dimensional.

In [ ]:
mb = 200
lb = 2.4
rb = 1.8
mp = 30
lp = 8
rp = 1
wp = np.array([
    [0.0175],
    [0],
    [0]
])
wb = np.array([
    [0],
    [0],
    [0.008]
])

J_body = np.array([
    [(1/4)*mb*rb**2+(1/3)*mb*lb**2, 0, 0],
    [0, (1/4)*mb*rb**2+(1/3)*mb*lb**2, 0],
    [0, 0, (1/2)*mb*rb**2]
])
print(J_body)
J_pannel = np.array([
    
])

[[546.   0.   0.]
 [  0. 546.   0.]
 [  0.   0. 324.]]
